<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InventoryService.Domain/InventoryService.Domain.csproj" />
    <ProjectReference Include="../../src/InventoryService.Application/InventoryService.Application.csproj" />
  </ItemGroup>
</Project>
